pub mod app;
pub mod bench;
pub mod config;
pub mod desktop;
pub mod effects;
#[cfg(feature = "glterm-spike")]
pub mod glterm;
#[cfg(feature = "freya-spike")]
pub mod gui;
#[cfg(feature = "freya-spike")]
pub mod gui_icons;
pub mod history;
pub mod hyprland;
pub mod icon;
pub mod input;
pub mod launcher;
pub mod launcher_core;
pub mod layout;
pub mod search;
#[cfg(feature = "freya-spike")]
pub mod spike_metrics;
#[cfg(feature = "freya-spike")]
pub mod term_host;
pub mod terminal;
pub mod terminal_resolver;
